# Generated by Django 4.0.2 on 2022-02-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat', '0003_alter_message_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='room_id',
        ),
    ]
