# Generated by Django 4.0.2 on 2022-02-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat', '0004_rename_room_message_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_id',
            new_name='city_id',
        ),
    ]
